### ISSUE TITLE
Firefox cannot use the script

### ISSUE THREAD

**Issue by morpheusthewhite** [Frewacom/Pywalfox#10]
I installed your script without any errors (the output is exactly the same on the README), but Firefox seems not to be able to use it; I already checked the troubleshooting section of the README none of the suggested conditions occurred. 

By looking at the console, after starting Firefox no error appears. But if I try to go to the plugin settings page, different errors are raised:
- On pressing "Fetch pywal colors" I get 
```
Error: Attempt to postMessage on disconnected port                                          [ background.js ]
```
- On pressing "Disable theme" 
```
TypeError: pywalColors is undefined                                                                        [ popup.js:74:5 ]
```
- When trying to check the "Background" box
```
TypeError: pywalColors is undefined                                                                        [ popup.js:141:13 ]
    highlightCurrentColorInDialog moz-extension://077f2ce1-4284-4184-a86a-74e4c6c2e09b/popup/popup.js:141
    openColorpickerDialog moz-extension://077f2ce1-4284-4184-a86a-74e4c6c2e09b/popup/popup.js:186

```

**Comment by Frewacom** [comment]
The TypeErrors you got is a side-effect of the colors not being fetched correctly. 

I have been looking around other similiar issues people have had with setting up the native app communication in Firefox and it could possibly be something with python. What happens if you run `env python` in your terminal?

**Comment by morpheusthewhite** [comment]
This is the output
```
$ env python
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
```

**Comment by Frewacom** [comment]
Did you restart Firefox after running `setup.sh`?

**Comment by JamesDalboth** [comment]
This is something I have also been experiencing. My python env is 3.6.9 and I have restarted firefox and my pc a few times in an attempt to get it working.

**Comment by Frewacom** [comment]
Could you post a screenshot of the Browser console (`Tools > Web developer > Browser Console`) after restarting Firefox?

**Comment by morpheusthewhite** [comment]
Yes, after some reboot everything works

**Comment by morpheusthewhite** [comment]
> Did you restart Firefox after running `setup.sh`?

Yes, even after restarting Firefox several times it didn't work

> Could you post a screenshot of the Browser console (`Tools > Web developer > Browser Console`) after restarting Firefox?

Yes, actually some error are still present even if now I am able to apply the theme. In particular the one I posted 

```
TypeError: pywalColors is undefined
```

**Comment by JamesDalboth** [comment]
![2020-03-23_220829-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367867-ebdb8700-6d52-11ea-88d3-8ab82741f06d.png)

The above is the screenshot of the console after restarting Firefox for me.

![2020-03-23_220838-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367894-fdbd2a00-6d52-11ea-907d-2d816b896fed.png)
Above is what happens after clicking fetch pywal colors.

**Comment by morpheusthewhite** [comment]
> ![2020-03-23_220829-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367867-ebdb8700-6d52-11ea-88d3-8ab82741f06d.png)
> 
> The above is the screenshot of the console after restarting Firefox for me.
> 
> ![2020-03-23_220838-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367894-fdbd2a00-6d52-11ea-907d-2d816b896fed.png)
> Above is what happens after clicking fetch pywal colors.

Same here

**Comment by Frewacom** [comment]
> > Did you restart Firefox after running `setup.sh`?
> 
> Yes, even after restarting Firefox several times it didn't work
> 
> > Could you post a screenshot of the Browser console (`Tools > Web developer > Browser Console`) after restarting Firefox?
> 
> Yes, actually some error are still present even if now I am able to apply the theme. In particular the one I posted
> 
> ```
> TypeError: pywalColors is undefined
> ```

Does all the functionality including the custom color picker work as expected? If it is, I am not quite sure why are getting those errors. I'll add some error handling for those cases either way.

**Comment by Frewacom** [comment]
> ![2020-03-23_220829-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367867-ebdb8700-6d52-11ea-88d3-8ab82741f06d.png)
> 
> The above is the screenshot of the console after restarting Firefox for me.
> 
> ![2020-03-23_220838-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77367894-fdbd2a00-6d52-11ea-907d-2d816b896fed.png)
> Above is what happens after clicking fetch pywal colors.

The errors you get is most likely because the native script could not be executed  correctly. The output I would like to see is the Browser console that comes when pressing Shift+Ctrl+J (not the inspector console).

**Comment by JamesDalboth** [comment]
![2020-03-23_222909-1xMar_scrot](https://user-images.githubusercontent.com/21280865/77369119-b84e2c00-6d55-11ea-8573-91d241a2629d.png)
Apologies, yes I can see the error `No such native application pywalfox`

**Comment by Frewacom** [comment]
That error indicates that the manifest is (most likely) not installed properly. 
> - Make sure that path in ~/.mozilla/native-messaging-hosts/pywalfox.json points to the location of daemon/pywalfox.py

**Comment by JamesDalboth** [comment]
Atm my path is "/home/james/Pywalfox/daemon/pywalfox.py".

```
{
  "name": "pywalfox",
  "description": "Automatically theme firefox using system colors generated by Pywal",
  "path": "/home/james/Pywalfox/daemon/pywalfox.py",
  "type": "stdio",
  "allowed_extensions": [ "pywalfox@frewacom.org" ]
}
```

I can confirm that it is the correct path as well

**Comment by Frewacom** [comment]
Hm, that is strange. Either way, the error indicates that the manifest is not installed properly (according to the Mozilla docs). Could it be some permission issue that denies read-access by Firefox?

**Comment by morpheusthewhite** [comment]
> Does all the functionality including the custom color picker work as expected? If it is, I am not quite sure why are getting those errors. I'll add some error handling for those cases either way.

Yes, they seem to work, even if after selecting a color the error said before is raised

```
Error: Could not establish connection. Receiving end does not exist.
```

If they can help you, here it is also the content of the debugging output
```
Theme was updated
Set custom color "background" to #ff4056
Theme was updated
Set custom color "background" to #0c101e
Theme was updated
Custom CSS: "hide-scrollbar.as.css" has been enabled
Custom CSS: "hide-scrollbar.as.css" has been disabled
Set custom color "background" to #cbbdc4
Theme was updated
Set custom color "background" to #0c101e
Theme was updated
Set custom color "background" to #2500b6
Theme was updated
Set custom color "background" to #0c101e
Theme was updated
Set custom color "background" to #a09a7e
Theme was updated
Set custom color "background" to #0c101e
Theme was updated
```

**Comment by morpheusthewhite** [comment]
> The errors you get is most likely because the native script could not be executed correctly. The output I would like to see is the Browser console that comes when pressing Shift+Ctrl+J (not the inspector console).

![image](https://user-images.githubusercontent.com/36999173/77398873-9631c980-6da8-11ea-81f7-eb6556d89770.png)

**Comment by Frewacom** [comment]
I actually have the exact same error from `background.js:1504` and for me it is coming from the Bitwarden extension, so it has nothing to do with Pywalfox. It is kind of annoying that the addon that causes the error is not written out along with the error.

**Comment by morpheusthewhite** [comment]
I actually use bitwarden, too

**Comment by JamesDalboth** [comment]
Since the errors seem to have diverged, I'm gonna redirect my problems to a new issue specific my issues.
