### ISSUE TITLE
Auto Mode not changing to dark/light

### ISSUE THREAD

**Issue by bergsm** [Frewacom/pywalfox#103]
Hello!

I seem to be having an issue with pywalfox auto mode not changing to light/dark automatically. I have auto mode set and I've set the interval as appropriate, however nothing happens after the time goes past the interval settings. If I make a change to the settings page, _then_ the mode will change.

Any ideas why this behavior may be occurring?

This is on FF 107.0.1. I also disabled any additional add-ons which I thought may conflict, but still have the same results.

Thanks for any help!

**Comment by Frewacom** [comment]
Hi,

It seems broken for me as well. Most likely this is the result of some other change, since the auto mode code has not been updated for over two years. I'll have a look when I find the time. 

Thanks!

**Comment by Frewacom** [comment]
I pushed a new commit to the `fix/auto-mode` branch that changes the auto mode to use the built-in Alarms API instead. I believe it should be working now, but I have not had the time to properly test it. 

Feel free to test it yourself and let me know if you find any issues. You can load the updated extension from the `about:debugging` page in Firefox by building the extension locally and selecting the `extension/manifest.json` file.

**Comment by Frewacom** [comment]
Should be fixed in latest version.
