### ISSUE TITLE
Auto mode, auto time

### ISSUE THREAD

**Issue by mjdvr** [Frewacom/Pywalfox#107]
Would it be possible to get sunrise and sunset times based on a geo-location?
This could be customized by the user, or set automatically by the use of browser geo-tracking.

**Comment by Frewacom** [comment]
This is definitely possible, but I don't think Firefox has any built-in API for this, so we would need to implement it ourselves. 

In the meantime, if you are using something like [redshift](https://github.com/jonls/redshift) or similar,  you could add a hook that is executed at sunrise/sunset and calls `pywalfox light`/`pywalfox dark` accordingly.
