### ISSUE TITLE
it not wroking at all

### ISSUE THREAD

**Issue by OneDAZAI** [Frewacom/pywalfox#108]
i did everything btw im runnig firefox deb pack last update 
![Screenshot from 2023-04-17 19-27-14](https://user-images.githubusercontent.com/114692357/232593354-b274d732-670b-440e-8c84-bb8f9acaf057.png)
![Screenshot from 2023-04-17 19-30-55](https://user-images.githubusercontent.com/114692357/232593456-984d4cc6-a309-4a48-bbfe-30cb6bb62dc3.png)

**Comment by Frewacom** [comment]
Hi,

Try the steps shown here https://github.com/Frewacom/pywalfox/issues/72#issuecomment-889239885.

**Comment by OneDAZAI** [comment]
![Screenshot from 2023-04-18 13-03-49](https://user-images.githubusercontent.com/114692357/232786279-0e0e3947-f580-4656-a5b0-8e31131c37a3.png)
![Uploading Screenshot from 2023-04-18 13-04-18.png…]()

nopeeee :((

**Comment by FelipeFTN** [comment]
I'm getting the same error, was you able to solve it?
