### ISSUE TITLE
Operation not permitted when installing (AUR version)

### ISSUE THREAD

**Issue by millionsofplayers** [Frewacom/pywalfox#126]
error:
` Successfully removed manifest at: /home/millions/.mozilla/native-messaging-hosts/pywalfox.json
Copied manifest to: /home/millions/.mozilla/native-messaging-hosts/pywalfox.json
Set daemon executable path to: /usr/lib/python3.12/site-packages/pywalfox/bin/main.sh
Failed to set executable permissions on: /usr/lib/python3.12/site-packages/pywalfox/bin/main.sh
	[Errno 1] Operation not permitted: '/usr/lib/python3.12/site-packages/pywalfox/bin/main.sh'

Try setting the permissions manually using: chmod +x `

chmod +x doesn't help, and running it as root copies it to the wrong directory

**Comment by Ewheeler121** [comment]
had the same issue, instead of 
```
sudo pywalfox install
``` 
do 

```
sudo -E pywalfox install
```

**Comment by millionsofplayers** [comment]
works, thanks
