### ISSUE TITLE
New icon for the addon 

### ISSUE THREAD

**Issue by Frewacom** [Frewacom/pywalfox#16]
Currently, the icon is just a black box with a "P" in it. It is not very good looking and there is only one size (48x48) as of now. 

The icon should be updated to a better looking one and include more [sizes](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons). 

It would be nice to display the icon/logo at the top of the README as well.

**Comment by Gusted** [comment]
What about a fox on a black background that is sitting and the inner colors are layered curved with diffrent color

**Comment by wts42** [comment]
Maybe a dynamic icon? Get the colors from the wallpaper color informations from pywal? (as a little gimmick)

**Comment by Gusted** [comment]
So far I know extension icons are static and couldn't be changes in the fly

**Comment by reeseovine** [comment]
Agreed, and I like @Gusted's suggestion of a rainbow fox. Though it might not be easy to see at small sizes so maybe just a fox face? I can mock up a draft of what I'm thinking.

For me I have the Privacy.com browser extension as well which looks nearly identical to Pywalfox's. Try to guess which one is which:

![2 browser add-on icons, both are a white capital letter P on a chamfered black square](https://user-images.githubusercontent.com/1340784/164984837-513105e1-9f11-4645-a58c-c9b657740462.png)

(To be fair I don't like Privacy's logo either, but of course I don't have the power to change it.)

**Comment by reeseovine** [comment]
Something like this look good?

![gradient fox](https://user-images.githubusercontent.com/1340784/164990764-fc18e372-5aff-496c-a8f7-320db4fb875c.png)

The gradient is on its own layer so it could be changed to anything

**Comment by Frewacom** [comment]
> Something like this look good?

Looks great! Perhaps the gradient could use a bit brighter colors to make it "pop" a bit more. 

I assume you made this yourself?

**Comment by reeseovine** [comment]
Like I said, the gradient could be anything, I just got tired of trying to make a rainbow as Inkscape's gradient editor leaves a lot to be desired.

And yes I did! I looked at some clip art of foxes for inspiration but the lines were 100% done by me.

I would like to work on the drawing some more since the face looks a bit human-like and it's creeping me out 😂

**Comment by reeseovine** [comment]
![gradient fox](https://user-images.githubusercontent.com/1340784/164999626-81922c93-856f-43eb-9b32-af9ffec8b8a2.png)

I just hid the mouth and eyes and I think it looks a lot better already. Let me know what you think!

**Comment by Frewacom** [comment]
Yeah, I really like it, and would gladly replace the current icon with this one 🦊. I am quite busy atm, but feel free to create a PR if you want!
