### ISSUE TITLE
Current tab Isn't Styled

### ISSUE THREAD

**Issue by Gusted** [Frewacom/Pywalfox#19]
![Screenshot from 2020-03-28 17-11-11](https://user-images.githubusercontent.com/25481501/77828416-94a33100-711b-11ea-8fa6-35d84900c3d4.png)
As you see the current Tab isn't styled and just white

**Comment by Frewacom** [comment]
It is styled, however, it uses the "Foreground" color and it is in most cases a very bright color. I personally prefer it that way, but you can change the default color that should be used by creating a custom template.

**Comment by Gusted** [comment]
Got it!
