### ISSUE TITLE
Light theme template

### ISSUE THREAD

**Issue by pranjlp** [Frewacom/pywalfox#21]
So I just created my own template for a light version from custom template option.

It would be nice if the addon could switch themes after sunset, using lat/long or time specified by the user.

A similar functionality exist in DarkReader for reference. They provide a time and latitude and longitude option.

**Comment by Frewacom** [comment]
It sounds like a good idea. I might add something like this in the next version. 

What does your light theme look like?

**Comment by pranjlp** [comment]
I am no expert in colors.  Used the firefox inbuilt light theme for inspiration.  

This is what I came up with:

Background: 15
Background light: 8
Text Color: 0
Foreground: 0
Accent Primary: 1
Accent Secondary: 14

Works with my setup for now.  There are a few corner cases. Like text selection needs to invert colors, which isn't required in Dark Mode.  DuckduckGo and new tab pages have some elements mis-colored.
