### ISSUE TITLE
Active tab color clashes with the theme

### ISSUE THREAD

**Issue by ReekyMarko** [Frewacom/pywalfox#22]
This might be a matter of taste, but no matter how many pywal colorschemes I have tried, i think using the foreground color for the background of the active tab is wrong. Thoughts?

Thanks for this plugin by the way, other than this issue, it's just awesome!

**Comment by Frewacom** [comment]
Agreed. I used to like the foreground color as tab background, but honestly, having it less bright is nicer. The foreground color will not be the default in version 2.0.0.

The default color for the tab can be changed using a custom template until I release the new version.
