### ISSUE TITLE
Not working in Pop!_OS (Ubuntu) 20.04, /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by Lau1406** [Frewacom/pywalfox#26]
Firstly: I've been using this with a lot of joy ever since I saw it on Reddit and want to thank the developers for this. 

The actual issue: since Pop!_OS 20.04 doesn't ship with python2 anymore (and probably Ubuntu as well), the script no longer functions as it uses the `python` command to invoke python (`#!/usr/bin/env python` in `pywalfox.py` line 1). However, only python3 is now a valid command (python2 is as well if you install python2 via apt). 
Temporary solution: run `sudo ln -s /usr/bin/python3 /usr/bin/python` to symlink python to python3 or install `python-is-python3` from apt (which does the same according to the discription)

**Comment by Frewacom** [comment]
This should be fixed in [`v2.0.0`](https://github.com/Frewacom/Pywalfox/tree/v2.0.0) since the entry point of the daemon is a bash script.  

I don't think I will fix it for the current version, since the next version will be finished quite soon and the workaround fix is very simple.

**Comment by Frewacom** [comment]
v2.0.0 has been released and this should hopefully not be an issue anymore. Closing for now.
