### ISSUE TITLE
v 2.0.1 is doing nothing

### ISSUE THREAD

**Issue by 0C3L0T** [Frewacom/pywalfox#29]
tried reinstalling pywalfox program, reinstalling addon and reinstaling firefox but to no avail.
http://0x0.st/ipNE.gif
the output of "pywalfox update":
`ERROR:root:Could not find socket: /tmp/pywalfox_socket`

**Comment by Frewacom** [comment]
Did you look at the Troubleshooting section of the README?

**Comment by 0C3L0T** [comment]
I did, made sure that:
-i reinstalled via the instructions
-i don't have permission errors when running pywalfox setup(http://0x0.st/ipq_.png)
-pywalfox log outputs `[05-23-2020 08:27:38] ERROR:Could not find default Firefox profile`
-~/.cache/wal/colors exists and contains hex color codes
-the browser cosole doesnt give errors

**Comment by Frewacom** [comment]
Hm, that is strange. If you navigate to `about:debugging` and click `Inspect` on the Pywalfox extension. Does the console show any errors?

**Comment by 0C3L0T** [comment]
yes, see: http://0x0.st/ipqF.png.

**Comment by Frewacom** [comment]
Okey, I found the issue. When running `pywalfox setup`, the manifest is installed to `~/.config/.mozilla/...`. It should just be `~/.mozilla/..`. I will push a fix for that soon.

**Comment by 0C3L0T** [comment]
awesome! XDG standards are a bitch am i right?

**Comment by Frewacom** [comment]
The fix should be uploaded to pip, so try running `pip install --upgrade pywalfox` and re-run the setup and things should hopefully work again.

**Comment by 0C3L0T** [comment]
works like a charm, cheers!

**Comment by nyex** [comment]
also it seems to be looking for colors in the wrong place:

`Pywal colors: Could not read colors from: /home/olivia/.config/.cache/wal/colors`

also an extra '.config' in the path there :)

**Comment by nyex** [comment]
nevermind, just did the upgrade, and it works! thanks!
