### ISSUE TITLE
Question: Color Variables

### ISSUE THREAD

**Issue by typkrft** [Frewacom/pywalfox#35]
Does pywal/pywalfox generate CSS color variables and are they able to be used in userChrome.css? If so is there a list of the CSS color variables somewhere?

**Comment by Frewacom** [comment]
Pywalfox does not generate any CSS variables, nor does it use CSS for theming (other than the included optional userChrome.css). 
However, Firefox has a few CSS variables that you can use, e.g: https://github.com/Frewacom/pywalfox-native/blob/master/pywalfox/assets/css/userChrome.css#L6. 

I have not looked into this too much, so you'll have to take a deep dive into the Browser inspector to find the other variables used by the theme (if they even exist).

**Comment by typkrft** [comment]
It looks like I can just find a browser element that pywalfox has colored, find for the color variable used, and apply it wherever. I may come back after I've got all the variables and what they correspond to on the palette, just in case anyone else from r/firefoxcss stumbles across this, and update this comment. Thanks for the help!
