### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by mclaughlinconnor** [Frewacom/pywalfox#36]
Title says it all really.

I have themes that change often, it would be useful to reload colours from PyWal without clicking manually. I think ideally you'd want to watch the PyWal colour file for changes and update automatically, though I think shortcuts would be far easier while still achieving a decent result.

**Comment by Frewacom** [comment]
You can use `pywalfox update` in your terminal/a script to automatically refetch the colors. I'll consider adding a keybinding as well.

**Comment by mclaughlinconnor** [comment]
Ah, thanks. This works for me, I'll leave open for now, though
