### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by fubarhouse** [Frewacom/pywalfox#38]
Given Mozilla Thunderbird is very closely aligned to Firefox - I would love for it to have a similar experience/look.
Just putting this out there as I've no idea what would be involved - but has this been requested before?

**Comment by Frewacom** [comment]
It seems like Thunderbird version >= 68 uses WebExtensions and therefore supports both the [Theming API and native communication API](https://thunderbird-webextensions.readthedocs.io/en/68/), so I assume it should work. 

I am not sure how much work is needed, but I will take a look.

**Comment by Frewacom** [comment]
I installed pywalfox as a temporary addon in Thunderbird and everything seems to be working with no modifications. It has been uploaded to the [Thunderbird addon store](https://addons.thunderbird.net/en-US/thunderbird/addon/pywalfox/).

The only issue I found is that if you are running Firefox and Thunderbird at the same time, two daemons will launch and only one of them will change theme when you run `pywalfox update`. 

Let me know if something is not working properly.

**Comment by fubarhouse** [comment]
Superb, thank you! 🎉
I'll test this tomorrow s as me let you know how it goes!

**Comment by fubarhouse** [comment]
This is working exactly as I hoped, so thank you very much!
Feel free to close the issue now 😄

**Comment by Frewacom** [comment]
The update issue should be fixed in daemon version [2.5](https://github.com/Frewacom/pywalfox-native/releases/tag/v2.5). You can update using pip. 

Closing this for now.

**Comment by Ninja73737** [comment]
Just one note on this, at least for me, I had to put the native messaging host .json in the global visibility location for MacOS as explained in this article: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests When it was just in the per-user Thunderbird didn't find it for some reason.

**Comment by Frewacom** [comment]
> Just one note on this, at least for me, I had to put the native messaging host .json in the global visibility location for MacOS as explained in this article: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests When it was just in the per-user Thunderbird didn't find it for some reason.

I added a `--global`flag to the Pywalfox CLI that can be used to install the manifest globally, rather than just locally. It has not been pushed to pip yet, but I will do that eventually. I'll also make sure this gets added to the Troubleshooting guide, in case someone else has the same issue.
