### ISSUE TITLE
highlighted text unreadable pywalfox thunderbird

### ISSUE THREAD

**Issue by zegheim** [Frewacom/pywalfox#40]
Hi,

I am currently using the latest version available in the add-ons website for both firefox and thunderbird. On firefox highlighted text automatically turns dark for readability purposes (see address bar below):

![image](https://user-images.githubusercontent.com/30282499/88505926-fc528580-d002-11ea-934d-1bd41297110d.png)

This is not the case when using the same theme on thunderbird, where highlighted text remains white and becomes unreadable. I was looking through thunderbird but there doesn't seem to be a way for me to access the pywalfox control panel unlike firefox?

![image](https://user-images.githubusercontent.com/30282499/88506013-33c13200-d003-11ea-9a16-a2effbb5e76f.png)

**Comment by Frewacom** [comment]
The icon should be visible in the main toolbar:
![thunderbird toolbar](https://user-images.githubusercontent.com/7253137/88519474-7595ac80-cff2-11ea-8804-b8d4cd505aea.png)

I am not sure why the text is not visible. For me it looks like this:
![mail highlight](https://user-images.githubusercontent.com/7253137/88519838-0c626900-cff3-11ea-9faa-52c372636c0e.png)

**Comment by fubarhouse** [comment]
I'm also not getting this. I had it set up in Firefox before and the button just appeared in ThunderBird.

I do have the system colours theme enabled, and the dark mode settings switched - so I would start by setting those.

I've just added a couple of new schemes too - so here's one:

![image](https://user-images.githubusercontent.com/3070264/88621738-90484e00-d0e4-11ea-8fde-e98e234f76b8.png)

**Comment by zegheim** [comment]
Very strange indeed - @fubarhouse I have enabled default theme and dark mode but no dice.

Might be worth mentioning that I am on the latest Thunderbird (78.0.1). Does this affect anything? The following is what I have on Menu > Preferences > Toolbar Layout:

![image](https://user-images.githubusercontent.com/30282499/88624600-781b0380-d0d1-11ea-9f0b-496a8d431ebc.png)

**Comment by Frewacom** [comment]
I had version 68 installed and installed both version 78 and the beta (79). No issues at all for me, so the version is probably not the issue. 

I am assuming that it is some setting(s) that you have? Perhaps you could try a different version and see if that makes a difference?

**Comment by zegheim** [comment]
Launching thunderbird on a new profile works fine! Thanks :)
