### ISSUE TITLE
Thunderbird pywal problem

### ISSUE THREAD

**Issue by nenxessence** [Frewacom/pywalfox#47]
Hi,
it is working with Thunderbird (Win10)? I followed the installation guide but i get this error:
I also installed pywal.

**Comment by Frewacom** [comment]
What are the contents of the file at the specified path? Most likely it contains invalid data/no data at all. Have you ran pywal on an image? If not, the file might not have been generated yet.

**Comment by nenxessence** [comment]
Can you send me an example of wal/colors file?

**Comment by Frewacom** [comment]
```
#0B0D0E
#318EC6
#788897
#B5C5BA
#2F85BB
#807E84
#5BA6D0
#c9dde4
#20272a
#2fbcff
#8ab1d5
#d2ffe8
#2db0ff
#a093bc
#62ddff
#eeffff
```

**Comment by nenxessence** [comment]
My fault sorry! Works! I only cannot change the colors of icons but everything looks good! Thanks for the amazing work!
![Capture](https://user-images.githubusercontent.com/26149965/95356010-7d14e400-08c6-11eb-9c3d-2b1d11f9eeeb.PNG)

**Comment by Frewacom** [comment]
No problem :)

Not all elements can be targeted using the Theme API, so there is not much I can do about that, sadly.
