### ISSUE TITLE
Error when fetching pywal colors

### ISSUE THREAD

**Issue by flber** [Frewacom/pywalfox#48]
I installed pywalfox, ran setup, restarted firefox and then tried to fetch my pywal colors, but was greeted with the error: `Fetch failed: You are not connected to the Pywalfox daemon`. I tried running `pywalfox daemon`, but it still wouldn't connect. I'm probably just doing something wrong here, but any guidance would be appreciated.

I'm running manjaro i3

**Comment by Frewacom** [comment]
Do you get any errors in the Browser console? 
Från: Ben Hammond <notifications@github.com>
Skickat: fredag 9 oktober 2020 22:41
Till: Frewacom/pywalfox
Kopia: Subscribed
Ämne: [Frewacom/pywalfox] Error when fetching pywal colors (#48)






I installed pywalfox, ran setup, restarted firefox and then tried to fetch my pywal colors, but was greeted with the error: Fetch failed: You are not connected to the Pywalfox daemon. I tried running pywalfox daemon, but it still wouldn't connect. I'm probably just doing something wrong here, but any guidance would be appreciated.

**Comment by flber** [comment]
I'm just getting two warnings:
`Use of nsIFile in content process is deprecated.`
`debuggee 'resource://devtools/shared/base-loader.js:289' would run`

**Comment by Frewacom** [comment]
That is strange. That error should only appear if the connection is broken (which should print an error in the Browser console) or if the response time exceeds the timeout delay. Is the native app version set in the debugging section of the Pywalfox setttings page?

**Comment by flber** [comment]
Yes, the version is set to 2.6 in the setting page, and it also says it is connected.

**Comment by Frewacom** [comment]
In that case I don't really know why it is not working as everything seems to be setup correctly. Have you tried fetching after waiting a little while? Sometimes it takes some time for Firefox to start the extension. 

You could also try entering this into the console of the Pywalfox settings page:

```javascript
await browser.storage.local.set({ connected: true });
```

and then try fetching the colors again.

**Comment by flber** [comment]
Ahhh. It just now worked (I didn't change anything). Not sure what happened, but I guess just waiting for a while is the way to go? Anyway, thank you for your help!
