### ISSUE TITLE
Text and background are same color for light themes

### ISSUE THREAD

**Issue by thraizz** [Frewacom/pywalfox#50]
When using pywalfox with light themes, the selected / active tab becomes unreadable as the font and background color are the same.
![screenshot](https://user-images.githubusercontent.com/30572790/97777439-7a797780-1b70-11eb-85e2-a6c59d6120b8.png)

**Comment by Frewacom** [comment]
You can change this color manually in the Pywalfox settings page to fix the issue. Most likely it is the wallpaper that causes this or your theme template (if you have changed it).

**Comment by Frewacom** [comment]
Did you manage to solve this?

**Comment by Frewacom** [comment]
Closing for now. Let me know if the issue persists and I will reopen it.

**Comment by dadaurs** [comment]
I'm experiencing the same issue, even though you can temporarily change the settings on the pywalfox interface, running `pywalfox update` or restarting firefox resets the colors, which make firefox almost unusable in light mode.

**Comment by Frewacom** [comment]
> I'm experiencing the same issue, even though you can temporarily change the settings on the pywalfox interface, running `pywalfox update` or restarting firefox resets the colors, which make firefox almost unusable in light mode.

You should be able to fix this by updating the palette template for light mode (select light mode and open the palette template dropdown). These settings will be persistent, even if you change wallpaper, restart Firefox or update the theme using `pywalfox update`.
