### ISSUE TITLE
Set mode (light/dark) from console

### ISSUE THREAD

**Issue by katacarbix** [Frewacom/pywalfox#51]
Would this be possible? You can already tell it to update the colors using the messaging host so I don't see why not.

**Comment by Frewacom** [comment]
Yes, it would be possible. I'll add it in the next update :+1:

**Comment by katacarbix** [comment]
Awesome, thank you so much!

**Comment by Frewacom** [comment]
This feature has been added to version [2.0.6](https://github.com/Frewacom/pywalfox/releases/tag/v2.0.6) of the addon and requires version >= [2.7.1](https://github.com/Frewacom/pywalfox-native/releases/tag/v2.7.1) of pywalfox-native.
