### ISSUE TITLE
Windows installation error with os geteuid

### ISSUE THREAD

**Issue by npdev453** [Frewacom/pywalfox#52]
Python 3.9.0

>   File "c:\users\np\appdata\local\programs\python\python39\lib\site-packages\pywalfox\install.py", line 219, in validate_permissions
> AttributeError: module 'os' has no attribute 'geteuid'

**Comment by Frewacom** [comment]
Seems like I forgot to test the `--global` flag on Windows. Apparently, `os.geteuid()` is only available on UNIX systems. I'll make sure to fix this in the next update.

**Comment by Frewacom** [comment]
Fixed in version [2.7.1](https://github.com/Frewacom/pywalfox-native/releases/tag/v2.7.1) of pywalfox-native.
