### ISSUE TITLE
pywalfox not creating ~/.cache/wal/colors

### ISSUE THREAD

**Issue by Cameron-Cn** [Frewacom/pywalfox#53]
First off, thank you for the work that's gone into the app! 

Probably a dumb error, it's likely I'm not doing something right&mdash;but I can't figure out what.

So far, I have installed both the addon and the `pywalfox` successfully, and the browser extension shows that it is connected under the "Debug" section.

I have run the commands that `pywalfox --help` ists (such as `pywalfox update'` but there have not been any folders created in `~/.cache`. I don't suspect a permissions issue, but it could very well be something so simple.

The log shows `ERROR: Could not read colors from: ~./cache/wal/colors.json` which makes sense, as it doesn't exist.

Many thanks again for any suggestions or solutions.

**Comment by Frewacom** [comment]
The file is generated by pywal, not by pywalfox. Generating a colorscheme using pywal should fix the issue :)

**Comment by Cameron-Cn** [comment]
Definitely a stupid problem, thank you for helping with that oversight!

Problem wholly resolved. Error was BKAC all along.
