### ISSUE TITLE
Tor Browser?

### ISSUE THREAD

**Issue by orangemn6** [Frewacom/pywalfox#56]
Is there a way to make this work  with tor browser? My friend uses tor and wants to do some ricing.

**Comment by Frewacom** [comment]
I see no reason as to why it wouldn't work. It would require you to manually install the native messaging manifest and probably modify the [main.sh](https://github.com/Frewacom/pywalfox-native/blob/master/pywalfox/bin/main.sh#L3) entrypoint with an absolute path to the pywalfox executable.

The manifest should be copied to `~/.local/share/torbrowser/tbb/x86_64/tor-browser_XXX/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/pywalfox.json` (might not be the exact same for your friend, but most likely there should be a `.mozilla/` in there somewhere). 

It would probably be easiest to run `pywalfox install` and then simply copy the `~/.mozilla/native-messaging-hosts` folder into `~/.local/share/torbrowser/tbb/x86_64/tor-browser_XXX/Browser/TorBrowser/Data/Browser/.mozilla`.

You can check the Browser console for errors if it does not work correctly.

**Comment by orangemn6** [comment]
That worked!  Thanks!
