### ISSUE TITLE
pywalfox install not working??

### ISSUE THREAD

**Issue by astrolul** [Frewacom/pywalfox#58]
when i type pywalfox install and hit enter i get the error ` zsh: command not found: pywalfox`.

How do i fix this??

**Comment by Frewacom** [comment]
If you installed via pip, you probably need to add the installation path for pip executables to your `$PATH`. For me, pip installs everything into `~/.local/bin`, but it might be different for you.

**Comment by astrolul** [comment]
how would i do this?? im a beginner to arch linux and dont know much about python lol.

**Comment by typkrft** [comment]
> how would i do this?? im a beginner to arch linux and dont know much about python lol.

--- 
Check if python and pip are installed 

```
$ python -V
Python 3.9.1   # Output should be the version of python installed

$ pip -V
pip 20.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9) # More output 
```

From the Main Page:
----
Installation

```
   pip install pywalfox
   pywalfox install
```

Get the Pywalfox add-on for
  - Firefox
  - Thunderbird
  
Restart Firefox and/or Thunderbird

Click the Pywalfox icon in the Firefox/Thunderbird UI to access the theme settings and click "Fetch Pywal colors". A theme matching your Pywal colors should now be applied.

The Python package installed through pip is the Pywalfox native messaging application, which fetches your Pywal colors for the Pywalfox add-on to use with the Theme API.

Please review the Troubleshooting section if something is not working correctly.

---

You can check if pywalfox is in your PATH

```
$ which pywalfox
/usr/local/bin/pywalfox   # As long as you don't see pywalfox not found you're good 
```

**Comment by Frewacom** [comment]
Thanks @typkrft! :1st_place_medal:

**Comment by Frewacom** [comment]
@astrolul Have you installed pywalfox using pip?

**Comment by McFrappe** [comment]
@astrolul 

I recommend reading up on python [here](https://www.python.org/about/gettingstarted/)

Python is can be found almost anywhere these days.

**Comment by astrolul** [comment]
> @astrolul Have you installed pywalfox using pip?

yup i have installed pywalfox using pip.

**Comment by Frewacom** [comment]
> > @astrolul Have you installed pywalfox using pip?
> 
> yup i have installed pywalfox using pip.

Check in `~/.local/bin` and see if there is any file named pywalfox in there. If so, you could either run it directly from there or add `~/.local/bin` to your PATH. 

Personally, I set the PATH in `~/.profile` by doing something like this:
```bash
export PATH="$PATH:$HOME/.local/bin"
```

The Arch wiki should have good instructions on how to do this if you get stuck. 

Another approach would be to simply run the following instead:
```
python -m pywalfox install
```

Though, it is probably a good idea to fix the PATH issue instead, since you will have this problem with everything else you install from pip.

**Comment by Frewacom** [comment]
@astrolul Did you manage to fix this?

**Comment by astrolul** [comment]
> @astrolul Did you manage to fix this?

Yes, I'll close this issue!
