### ISSUE TITLE
> how would i do this?? im a beginner to arch linux and dont know much about python lol.

### ISSUE THREAD

**Issue by astrolul** [Frewacom/pywalfox#59]
> how would i do this?? im a beginner to arch linux and dont know much about python lol.

--- 
Check if python and pip are installed 

```
$ python -V
Python 3.9.1   # Output should be the version of python installed

$ pip -V
pip 20.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9) # More output 
```

From the Main Page:
----
Installation

1.

```
   pip install pywalfox
   pywalfox install
```

2. Get the Pywalfox add-on for
  - Firefox
  - Thunderbird
  
3. Restart Firefox and/or Thunderbird

4. Click the Pywalfox icon in the Firefox/Thunderbird UI to access the theme settings and click "Fetch Pywal colors". A theme matching your Pywal colors should now be applied.

The Python package installed through pip is the Pywalfox native messaging application, which fetches your Pywal colors for the Pywalfox add-on to use with the Theme API.

Please review the Troubleshooting section if something is not working correctly.

---

You can check if pywalfox is in your PATH

```
$ which pywalfox
/usr/local/bin/pywalfox   # As long as you don't see `pywalfox not found` you're good 
```

_Originally posted by @typkrft in https://github.com/Frewacom/pywalfox/issues/58#issuecomment-757981776_

**Comment by Frewacom** [comment]
Keep the discussion to the original issue #58. This is not really related to pywalfox, but rather an issue with your setup.
