### ISSUE TITLE
colors.json is not found error in Windows 10 with Thunderbird 78

### ISSUE THREAD

**Issue by Bappamaiti** [Frewacom/pywalfox#61]
Hello Dear Pywalfox team,

Thank you for this tool.

 **After installation I am currently facing this issue.**
1st.
This is the color generation SS, from which it looks like some error occurred, but don't know why-
![image](https://user-images.githubusercontent.com/81735229/114659993-2d4e2400-9d12-11eb-99bd-c10b0df08a73.png)

2nd.
This is the error screen of the pywalfox, which shows no color.json file found.
![image](https://user-images.githubusercontent.com/81735229/114660258-9e8dd700-9d12-11eb-973e-e739598f3753.png)

and 
Below is the location from the error
![image](https://user-images.githubusercontent.com/81735229/114661469-b23a3d00-9d14-11eb-9ea3-2cbea56ff872.png)

So, Please help to resolve this issue.

Thank You!

**Comment by Frewacom** [comment]
Hello,

Pywalfox can not find your colorscheme because pywal crashed during execution. It seems to be some issue with the `magick` module. Take a look at the pywal Github page to see if anyone has had the same issue. 

If you manage to get pywal working, then Pywalfox should start working as well 💯

**Comment by Bappamaiti** [comment]
> Hello,
> 
> Pywalfox can not find your colorscheme because pywal crashed during execution. It seems to be some issue with the `magick` module. Take a look at the pywal Github page to see if anyone has had the same issue.
> 
> If you manage to get pywal working, then Pywalfox should start working as well 💯

Hello Sir,
Thank you for your quick response.

I will check with the pywal repository as advised and will update here if resolved.

Thanks again.

**Comment by Frewacom** [comment]
Can I close this?

**Comment by Bappamaiti** [comment]
> Can I close this?

Yes please.
