### ISSUE TITLE
Pywalfox executable not working for me!!!

### ISSUE THREAD

**Issue by Wizard451345** [Frewacom/pywalfox#69]
Hello!

When running the executable I get these errors!!!

`06:51:33 pi@raspberrypi ~ pywalfox
Traceback (most recent call last):
  File "/home/pi/.local/bin/pywalfox", line 6, in <module>
    from pywalfox.__main__ import main
  File "/home/pi/.local/lib/python2.7/site-packages/pywalfox/__main__.py", line 8, in <module>
    from .daemon import Daemon
  File "/home/pi/.local/lib/python2.7/site-packages/pywalfox/daemon.py", line 5, in <module>
    from .fetcher import get_pywal_colors
  File "/home/pi/.local/lib/python2.7/site-packages/pywalfox/fetcher.py", line 3, in <module>
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError
06:51:42 pi@raspberrypi ~ `

Not sure if its important but does have to do with the arm architecture or something? I am a noob not sure if this helps...

**Comment by Frewacom** [comment]
Most likely caused by your python version, but it seems like I can fix this quite easily by not using `JSONDecodeError`, and instead using `ValueError`.

I will test the solution above and push a new release 👍🏼

**Comment by Frewacom** [comment]
I just pushed a test release that you can try:

```
pip uninstall pywalfox
pip install --index-url https://test.pypi.org/simple/ pywalfox==2.7.4rc1
```

Please let me know if everything seems to be working as expected.

**Comment by Wizard451345** [comment]
I'm in!
