### ISSUE TITLE
How to genterate colors.json

### ISSUE THREAD

**Issue by Darth-Ness** [Frewacom/pywalfox#79]
I can't set it up

**Comment by Frewacom** [comment]
`colors.json` is created by [pywal](https://github.com/dylanaraps/pywal) whenever you generate a colorscheme. 

In general, usage of pywal and pywalfox will be something like this:

```bash
wal -i <path-to-img> # generate colorscheme 
pywalfox update # update Firefox theme
```

**Comment by Darth-Ness** [comment]
Thanks! That fixed it!
