### ISSUE TITLE
Quite a few sites do not work with this browser

### ISSUE THREAD

**Issue by Ericjar** [Frewacom/pywalfox#80]
Too many sites don't work
Just a couple... (and I did try it after disabling the ad blocker)
Accuweather maps https://www.accuweather.com/en/us/princess-anne/21853/weather-radar/333540
Local TV listings (time is way off see attachment 6:00 news listed at 11PM ) https://www.tvtv.us/md/salisbury/21801/lu10201

![Screenshot from 2021-11-22 08-10-19](https://user-images.githubusercontent.com/35229859/142868344-fef80342-b54c-46a1-9019-9b619d11a645.png)

**Comment by Frewacom** [comment]
I think there has been a misunderstanding as to what the addon is supposed to do, so I will close the issue. Let me know if you want it reopened, or if you have any other questions.
