### ISSUE TITLE
Native messenger connection error on NixOS

### ISSUE THREAD

**Issue by TripleK2004** [Frewacom/pywalfox#82]
I have installed the latest version of pywalfox on PyPi on NixOS and the socket seem to work properly with the verbose mode enabled. And the socket is also active in /tmp , but the extension doesnt seem to find the binary or the socket ? 
I also had to remove the function which makes `main.sh` executable sincet nix uses an immutable file system. But i am later making the script executable later

The following error occured when trying to connect to the native messenger: None

pywalfox binary is in $PATH and the socket in /tmp , what else is required for pywalfox extension to function ?

![image](https://user-images.githubusercontent.com/76064725/155012609-4e354d3e-9d29-4b09-88f8-c96f740f24f9.png)

and i am getting `ERROR:root:Failed to connect to socket: Connection refused` upon update

**Comment by Frewacom** [comment]
Firefox probably does not have the executable in its PATH when it is running (even though you have it correctly setup). You should be able to confirm this by looking at the Browser Console. 

There is another version of the native messenger that is currently only available from the test repository of PyPi (see 
https://github.com/Frewacom/pywalfox/issues/68#issuecomment-873381669). This version starts the pywalfox executable directly using an absolute path, thus you should have no issues with `main.sh`. Hopefully, it should fix the connection error as well.

**Comment by TripleK2004** [comment]
> Firefox probably does not have the executable in its PATH when it is running (even though you have it correctly setup). You should be able to confirm this by looking at the Browser Console.
> 
> There is another version of the native messenger that is currently only available from the test repository of PyPi (see [#68 (comment)](https://github.com/Frewacom/pywalfox/issues/68#issuecomment-873381669)). This version starts the pywalfox executable directly using an absolute path, thus you should have no issues with `main.sh`. Hopefully, it should fix the connection error as well.

Yep that works, thanks mate : )
