### ISSUE TITLE
Set execute permissions on daemon executable

### ISSUE THREAD

**Issue by skinatro** [Frewacom/pywalfox#86]
I am using arch linux and zsh shell

I tried the removing native-messaging-hosts fix, chowning it
I also tried installing it via pip and AUR
but it still gives me this error

```
➜  ~ pywalfox install                       
Copied manifest to: /home/kuroneko/.mozilla/native-messaging-hosts/pywalfox.json
Set daemon executable path to: /home/kuroneko/.local/lib/python3.10/site-packages/pywalfox/bin/main.sh
Set execute permissions on daemon executable
```
I also went to the daemon executable path and verified that main.sh is executable and also did a `chown +x` but the error persists

**Comment by Frewacom** [comment]
The installer is not actually complaining about anything, it just tells you want it has done. To me, it seems like everything is working as expected. Is the Pywalfox addon not working for you?

**Comment by skinatro** [comment]
It was working but i was worried about the error message.
Since it isnt something to worry about, i will close the issue.
Thank you for time in replying to me and  making this project 😃
