### ISSUE TITLE
any ides on how to use with firefox-developer-edition?

### ISSUE THREAD

**Issue by golam71** [Frewacom/pywalfox#91]

**Comment by Frewacom** [comment]
What is the difference compared to regular Firefox?

**Comment by golam71** [comment]
it cant fetch colors

**Comment by Frewacom** [comment]
I think the native messenger is just not setup properly. Check for errors in the browser console, as desribed here: https://github.com/Frewacom/pywalfox#-common-errors-in-the-browser-console

**Comment by golam71** [comment]
yeah works now
clean install of both pywalfox and firefox dev edition
thanx
