### ISSUE TITLE
Firefox long loading time

### ISSUE THREAD

**Issue by Sancoraa** [Frewacom/pywalfox#97]
Hello !

Whenever there's a Firefox update or when I boot Firefox for the first time after my PC boots, it takes up to 2 minutes to load a webpage. Once a webpage is loaded every next webpage will load fast just like it's supposed to.
Turns out this issue is caused by Pywalfox. After disabling it everything works fine.

Using version 2.0.8 from Mozilla's addons webpage, running on Linux (EndeavourOS) and i3. If there's any way I can provide you logs I'd be glad to help you

**Comment by Frewacom** [comment]
Hi,

Have you enabled the "Fetch colors on startup" option on the Pywalfox settings page? If so, try disabling it and see if the issue still persists. 

You could also try to have a look at the Browser Console (Tools > Web developer > Browser console) and see if there is any new output once the webpage finally loads. That could possibly give an indication as to what is taking so much time.

**Comment by Sancoraa** [comment]
Hi ! Seems like I did not test enough before sending an issue. I've just rebooted my PC and the issue still occurs even when pywalfox is disabled, which means it does not come from your extension.

Sorry for the inconvenience !

**Comment by Frewacom** [comment]
Alright, no problem 👍🏼
