### ISSUE TITLE
Failed to set executable permissions etc, try settings permissions manually

### ISSUE THREAD

**Issue by g1sbi** [Frewacom/pywalfox#99]
I'm on Arch, I followed all the steps until `pywalfox install`, where I get this error:
```
Successfully removed manifest at: /home/gisbi/.mozilla/native-messaging-hosts/pywalfox.json
Copied manifest to: /home/gisbi/.mozilla/native-messaging-hosts/pywalfox.json
Set daemon executable path to: /usr/lib/python3.10/site-packages/pywalfox/bin/main.sh
Failed to set executable permissions on: /usr/lib/python3.10/site-packages/pywalfox/bin/main.sh
        [Errno 1] Operation not permitted: '/usr/lib/python3.10/site-packages/pywalfox/bin/main.sh'

Try setting the permissions manually using: chmod +x
```
I tried doing a `chown` on the .mozilla directory and also a `chmod +x` on the script like suggested, but I still get the same error.

**Comment by Frewacom** [comment]
Once you have set the permissions manually, everything should be ok. No need to re-run `pywalfox install`. Does the extension work as expected for you?

**Comment by g1sbi** [comment]
It didn't before but it does now. No idea why but thank you!
